#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');

program
  .version('0.0.1')
  .option('-a, --add', 'Add numbers')
  .option('-p, --peppers', 'Add peppers')
  .option('-P, --pineapple', 'Add pineapple')
  .option('-b, --bbq', 'Add bbq sauce')
  .option('-c, --cheese <type>', 'Add the specified type of cheese [marble]')
  .option('-C, --no-cheese', 'You do not want any cheese')
  .parse(process.argv);

console.log('you ordered a pizza with:');
if (program.peppers) console.log('  - peppers');
if (program.pineapple) console.log('  - pineapple');
if (program.bbq) console.log('  - bbq');

if (program.add) {
	console.log ('')
	var numbers = program.args;
	var firstNumber = parseInt(numbers[0]);
	var	secondNumber = parseInt(numbers[1]);
	var sum = firstNumber + secondNumber;
	
	console.log('adding %d and %d equals %d', firstNumber, secondNumber, sum);
}

var cheese = true === program.cheese
  ? 'marble'
  : program.cheese || 'no';




